# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter1: 1

services:
#    app.jet.api:
#        class: AppBundle\Services\JetApi
#        arguments: ["%parameter1%"]

    app.jet.process:
            class: AppBundle\Controller\ProcessController
#            arguments: ["%parameter1%"]
