# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter1: 1

services:
#    app.jet.route:
#        class: AppBundle\Services\MyRoute
#        arguments: ['%kernel.root_dir%']

    app.jet.process:
            class: AppBundle\Controller\ProcessController
#            arguments: ["%parameter1%"]
